=== transformerlab/galleries/schemas/models.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "uniqueID": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "description": {
        "type": "string"
      },
      "parameters": {
        "type": "string"
      },
      "context": {
        "type": "string"
      },
      "architecture": {
        "enum": [
          "CohereForCausalLM",
          "DeepseekV3ForCausalLM",
          "FalconForCausalLM",
          "GemmaForCausalLM",
          "Gemma2ForCausalLM",
          "Gemma3ForCausalLM",
          "Gemma3ForConditionalGeneration",
          "ShieldGemmaForImageClassification",
          "GGUF",
          "GPTBigCodeForCausalLM",
          "GraniteForCausalLM",
          "LlamaForCausalLM",
          "Llama4ForConditionalGeneration",
          "LlavaForConditionalGeneration",
          "MistralForCausalLM",
          "MixtralForCausalLM",
          "MLX",
          "PhiForCausalLM",
          "Phi3ForCausalLM",
          "Qwen2ForCausalLM",
          "Qwen3ForCausalLM",
          "Qwen3MoeForCausalLM",
          "T5ForConditionalGeneration",
          "Cohere2ForCausalLM",
          "ExaoneForCausalLM",
          "Mistral3ForConditionalGeneration",
          "AprielForCausalLM"
        ]
      },
      "huggingface_repo": {
        "type": "string"
      },
      "huggingface_filename": {
        "type": "string"
      },
      "transformers_version": {
        "type": "string"
      },
      "license": {
        "type": "string"
      },
      "logo": {
        "type": "string"
      },
      "author": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "blurb": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "url",
          "blurb"
        ]
      },
      "resources": {
        "type": "object",
        "properties": {
          "canonicalUrl": {
            "type": "string"
          },
          "downloadUrl": {
            "type": "string"
          },
          "paperUrl": {
            "type": "string"
          }
        },
        "required": [
          "canonicalUrl",
          "downloadUrl",
          "paperUrl"
        ]
      }
    },
    "required": [
      "uniqueID",
      "name",
      "parameters",
      "architecture",
      "huggingface_repo",
      "license"
    ]
  }
}

=== transformerlab/galleries/models/MLX.json
[
    {
        "uniqueID": "mlx-community/Mistral-7B-Instruct-v0.1-4bit-mlx",
        "name": "Mistral-7B-Instruct-v0.1 MLX 4bit",
        "description": "The Mistral-7B-Instruct-v0.1 Large Language Model (LLM) is a instruct fine-tuned version of the Mistral-7B-v0.1 generative text model using a variety of publicly available conversation datasets.",
        "parameters": "7B",
        "context": "4k",
        "architecture": "MLX",
        "huggingface_repo": "mlx-community/Mistral-7B-Instruct-v0.1-4bit-mlx",
        "transformers_version": "4.34.0.dev0",
        "license": "Apache 2.0",
        "logo": "https://docs.mistral.ai/img/logo.svg",
        "author": {
            "name": "Mistral AI",
            "url": "https://docs.mistral.ai/",
            "blurb": ""
        },
        "resources": {
            "canonicalUrl": "https://huggingface.co/mistralai/Mistral-7B-v0.1",
            "downloadUrl": "https://huggingface.co/mistralai/Mistral-7B-v0.1",
            "paperUrl": "?"
        }
    }
]

=== transformerlab/galleries/models/llama.json
[
    {
        "uniqueID": "huggyllama/llama-7b",
        "name": "HuggyLLama LLama 7B",
        "description": "Best overall smaller model. Fast responses. Instruction based. Trained by TII. Licensed for commercial use.",
        "parameters": "7B",
        "context": "4k",
        "architecture": "FalconForCausalLM",
        "huggingface_repo": "huggyllama/llama-7b",
        "transformers_version": "4.27.4",
        "license": "Meta Custom",
        "logo": "https://upload.wikimedia.org/wikipedia/commons/a/ab/Meta-Logo.png",
        "author": {
            "name": "Meta",
            "url": "https://huggingface.co/meta-llama/",
            "blurb": ""
        },
        "resources": {
            "canonicalUrl": "https://huggingface.co/huggyllama/llama-7b",
            "downloadUrl": "https://huggingface.co/huggyllama/llama-7b",
            "paperUrl": "?"
        }
    }
]

=== transformerlab/galleries/models/nous-hermes.json
[
    {
        "uniqueID": "Nous-Hermes-13b",
        "name": "Nous Hermes 13b",
        "description": "Extremely good model. Instruction based. Gives long responses. Curated with 300,000 uncensored instructions. Trained by Nous Research. Cannot be used commercially",
        "parameters": "13B",
        "context": "?",
        "architecture": "LlamaForCausalLM",
        "huggingface_repo": "NousResearch/Nous-Hermes-13b",
        "transformers_version": "4.29.2",
        "license": "GPL",
        "logo": "https://aeiljuispo.cloudimg.io/v7/https://cdn-uploads.huggingface.co/production/uploads/62fc06a221c444a56f7cc595/ngyQKdhaykfC8lN6Jfqlz.png?w=200&h=200&f=face",
        "author": {
            "name": "Nous Research",
            "url": "https://nousresearch.com/",
            "blurb": "We are dedicated to advancing the field of natural language processing, in collaboration with the open-source community, through bleeding-edge research and a commitment to symbiotic development."
        },
        "resources": {
            "canonicalUrl": "https://huggingface.co/lmsys/vicuna-7b-v1.5",
            "downloadUrl": "https://huggingface.co/lmsys/vicuna-7b-v1.5",
            "paperUrl": "?"
        }
    }
]
